spring.application.name=understand-google-login-with-webapp
server.port=8080
# Logback it won appear on console if you don't specify level
logging.level.root[0] = info
logging.level.root[1] = debug
spring.config.import=classpath:info/google_api_developer.properties